import mongoose, { Schema, type InferSchemaType } from 'mongoose';

export const Roles = ['user', 'admin'] as const;
export type Role = (typeof Roles)[number];

export const SkillLevels = ['beginner', 'intermediate', 'advanced'] as const;
export type SkillLevel = (typeof SkillLevels)[number];

const userSchema = new Schema(
    {
        // Unique, immutable user id is automatically generated by MongoDB as _id

        username: {
            type: String,
            required: true,
            trim: true,
            minlength: 3,
            maxlength: 30,
            unique: true,
        },
        email: { type: String, required: true, trim: true, lowercase: true, unique: true },

        passwordHash: { type: String, required: true },

        role: { type: String, enum: Roles, default: 'user' },

        preferredLanguages: { type: [String], default: [] },

        skillLevel: { type: String, enum: SkillLevels, default: 'beginner' },
    },
    { timestamps: true }, // Add createdAt and updatedAt fields automatically
);

// Exclude passwordHash from JSON output
userSchema.set('toJSON', {
    transform: (_doc, ret) => {
        const obj: any = { ...ret };
        delete obj.passwordHash;
        return obj;
    },
});

export type User = InferSchemaType<typeof userSchema>;
export const UserModel = mongoose.model('User', userSchema);
